import React from 'react'
import Head from 'next/head'
import Navigation from '../components/Navigation'
import styles from '../styles/editor.module.scss'
import PostEditor from '../components/PostEditor'
import InfoModal from "../components/InfoModal"

// TODO: make it rich text editor

// article page
export default function MyEditor({ post }) {
    const [isModal, setModal] = React.useState(false);

    return (
        <div className={styles.container}>
            <Head>
                <title>Post Page</title>
                <meta charSet="utf-8" name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navigation></Navigation>
            {isModal && <InfoModal />}
            <div className={styles.main}>
                <h2>Share Your Story...</h2>
                <PostEditor setPosting={setModal}></PostEditor>
            </div>
        </div>
    )
}